### ISSUE TITLE
Github Pages is disabled

### ISSUE THREAD

**Issue by fredster33** [Genius-Bot/genius-bot.github.io#1]
You can enable it in Organization Settings or this repo's settings.

**Comment by fredster33** [comment]
I'd also like to comment that you disabled a lot of organization member permissions and that makes some things harder to manage on my side.

**Comment by Geige2** [comment]
Ok, sorry, what should I change?

**Comment by Geige2** [comment]
Also how do I setup an MIT license?

**Comment by Geige2** [comment]
also, https://github.com/Genius-Bot/genius_bot/tree/main/WebApp/GeniusBotWebsite

**Comment by fredster33** [comment]
The website folder is nice. GitHub Pages is just a hosting platform for static sites.

**Comment by fredster33** [comment]
I can give some specific instructions later.

**Comment by fredster33** [comment]
Right now all the code is licensed under [no license.](https://choosealicense.com/no-permission/)

**Comment by fredster33** [comment]
ChooseALicense.com (maintained by GitHub and the community) has some good information on licensing and the MIT license: https://choosealicense.com/licenses/mit/

**Comment by Geige2** [comment]
Thanks! And how about the settings?

**Comment by Geige2** [comment]
So I just add a LICENSE FILE and copy that text in with those small changes?

**Comment by fredster33** [comment]
Preferably LICENSE.md. Make sure you understand the implementations of adding a license.

**Comment by Geige2** [comment]
Ok, but do I need to apply for it? Also, what settings should I change to make it easier for you to manage projects?

**Comment by fredster33** [comment]
You don't need to apply for the license.

**Comment by Geige2** [comment]
Cool! What about the settings?

**Comment by Geige2** [comment]
I've changed some settings, hopefully that helps.
